# Generated by Django 3.2.12 on 2022-02-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='ward',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='care.ward'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
