# Generated by Django 3.2.12 on 2022-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_alter_patient_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
