# Generated by Django 3.2.12 on 2022-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0007_ward_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
