# Generated by Django 3.2.12 on 2022-03-04 11:09

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0010_temporarylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='timestamp',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporarylink',
            name='token',
            field=models.CharField(default='il0TJ3hZQGa4GKWcOqdT5VYwQBWLLp', max_length=30),
        ),
    ]
