# Generated by Django 3.2.12 on 2022-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0011_auto_20220304_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='visit',
            new_name='notes',
        )
    ]
