# Generated by Django 3.2.12 on 2022-03-05 10:01

import care.models.misc
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0012_auto_20220304_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdisease',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdisease',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='care.treatment'),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporarylink',
            name='token',
            field=models.CharField(default=care.models.misc.generate_token, max_length=30),
        ),
    ]
