# Generated by Django 3.2.12 on 2022-02-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220227_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PN', 'Primary Nurse'), ('SN', 'Secondary Nurse'), ('DA', 'District Admin')], max_length=3),
        ),
    ]
